version: '3'
services:
  mongo:
    image: mongo:4.0.6
    container_name: mongo-node
  redis:
    image: redis:5.0.3
    container_name: redis-node
  monitor:
    build: .
    image: monitor
    container_name: monitor-node
    environment:
      # Read from ".env" file.
      - BITMEX_ACCOUNT_ID=${BITMEX_ACCOUNT_ID}
      - BITMEX_API_KEY=${BITMEX_API_KEY}
      - BITMEX_API_SECRET=${BITMEX_API_SECRET}
      - INITIAL_SLEEP_SECONDS=0
      - LOOP_INTERVAL_SECONDS=1.25
    depends_on:
      - mongo
      - redis
